import type { NextPage } from "next"
import Head from "next/head"

const PosterCreator: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Poster creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Poster creator
        </h1>
      </main>
    </div>
  )
}

export default PosterCreator
